spring:
  datasource:
    url: jdbc:mysql://182.92.61.75:3306/gmall?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 8071

dubbo:
  application:
    name: manage-service
  registry:
    address: zookeeper://182.92.61.75:2181
  scan:
    base-packages: com.example.gmall

logging:
  level:
    com.example.gmall: debug
